# Generated by Django 3.1.2 on 2020-11-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_openingmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingmessage',
            old_name='user',
            new_name='owner',
        ),
    ]
