# Generated by Django 3.1.2 on 2020-11-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='users_profile',
        ),
    ]
