# Generated by Django 3.1.2 on 2020-11-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userprofile_avatar'),
        ('account', '0011_auto_20201109_2348'),
    ]

    operations = [
    ]
