# Generated by Django 3.1.2 on 2020-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201112_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_interests', to='account.Interest'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterModelTable(
            name='interest',
            table='all_interests',
        ),
    ]
