# Generated by Django 3.1.2 on 2020-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20201112_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
