# Generated by Django 3.1.2 on 2020-11-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20201115_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('req_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_from', to='account.userprofile')),
                ('req_opening_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.openingmessage')),
                ('req_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_to', to='account.userprofile')),
            ],
            options={
                'db_table': 'Requests',
                'unique_together': {('req_from', 'req_to', 'req_opening_message')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requests',
            field=models.ManyToManyField(related_name='chat_requests', through='account.RequestModel', to='account.UserProfile'),
        ),
    ]
