# Generated by Django 3.1.2 on 2020-11-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20201115_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=20)),
                ('opening_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.openingmessage')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_from', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Requests',
                'unique_together': {('source', 'target', 'opening_message')},
            },
        ),
    ]
