# Generated by Django 3.1.2 on 2020-11-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20201121_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='accepted',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='req_state',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
