# Generated by Django 3.1.2 on 2020-12-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20201127_1858'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interest',
            table='interests',
        ),
        migrations.AlterModelTable(
            name='openingmessage',
            table='opening_messages',
        ),
        migrations.AlterModelTable(
            name='requestmodel',
            table='requests',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
