# Generated by Django 3.1.2 on 2020-11-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_requestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='message',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
