# Generated by Django 3.1.2 on 2021-02-06 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0019_auto_20201225_2043'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default=None, max_length=255, null=True)),
                ('avatar', models.ImageField(upload_to='pictures/avatars/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='MyChatUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(default='member', max_length=30)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.mychat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_user_info',
            },
        ),
        migrations.CreateModel(
            name='MyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='chat.mychatuserinfo')),
                ('replied_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.mymessage')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.AddField(
            model_name='mychat',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.MyMessage'),
        ),
        migrations.AddField(
            model_name='mychat',
            name='opening_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.openingmessage'),
        ),
    ]
