# Generated by Django 3.1.2 on 2021-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychat',
            name='avatar',
            field=models.ImageField(null=True, upload_to='pictures/avatars/'),
        ),
    ]
