# Generated by Django 3.1.2 on 2021-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210206_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/avatars/'),
        ),
        migrations.AlterField(
            model_name='mychat',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
