# Generated by Django 3.1.2 on 2020-12-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
